### ISSUE TITLE
Add DB Methods

### ISSUE THREAD

**Issue by Llewxamris** [Llewxamris/thor-hvk-assignment03#11]
Add methods to the DB class library in the appropriate classes that will retrieve information required to determine if a reservation can be made and insert/update records in the appropriate database tables. These methods can be overloaded if you want to use the same method with differing sets of parameters.  Once again, these methods in the DB class library should be suffixed with DB. 

- #14 @TPlouffe [ ]
- #13 Myself [ ]
- #12 @Potatoses555 [ ]

**Comment by Llewxamris** [comment]
Individual issues created for the exact methods we each will work on.

**Comment by Llewxamris** [comment]
Currently distributed based on which who wrote the test description.

**Comment by Llewxamris** [comment]
#14 @TPlouffe 
#13 Myself
#12 @Potatoses555

**Comment by TPlouffe** [comment]
Added add methods to DB level
